### ISSUE TITLE
Alba assertion fails using .NET 9

### ISSUE THREAD

**Issue by Zsolt-Bendes** [JasperFx/alba#178]
Assertion fails when using .NET 9. with error message:
```
Alba.ScenarioAssertionException : Expected status code 400, but was 500


Actual body text was:

System.InvalidOperationException: The PipeWriter 'ResponseBodyPipeWriter' does not implement PipeWriter.UnflushedBytes.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_PipeWriterDoesNotImplementUnflushedBytes(PipeWriter pipeWriter)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsync(PipeWriter pipeWriter, T rootValue, Int32 flushThreshold, CancellationToken cancellationToken, Object rootValueBoxed)
   at Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.<WriteAsJsonAsync>g__WriteAsJsonAsyncSlow|5_0[TValue](HttpResponse response, TValue value, JsonTypeInfo`1 jsonTypeInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResults.ProblemHttpResult.ExecuteAsync(HttpContext httpContext)
   at Internal.Generated.WolverineHandlers.POST_projects.Handle(HttpContext httpContext)
   at Internal.Generated.WolverineHandlers.POST_projects.Handle(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

[According to this](https://github.com/dotnet/runtime/issues/108075) the package needs to be updated. 

I know you guys are busy running a business, but I do hope some from JasperFx team will have time at some point to take a look.
Just wanted to make sure you know about this.

I really like Alba and other JasperFx libaries! Keep the awsome work!

**Comment by WalhallaZ** [comment]
@Zsolt-Bendes for me, the fix described here helped (install nuget package Microsoft.AspNetCore.Mvc.Testing v9.0.0): https://github.com/dotnet/runtime/issues/108075

**Comment by discoaaron** [comment]
Hello, I ran into the same issue.
To workaround this issue I added Microsoft.AspNetCore.Mvc.Testing version 9.0.0 as a direct dependency in my test project. 
I believe this forces alba to get the direct dependency instead of it's transient dependency which fixes my tests.

**Comment by Zsolt-Bendes** [comment]
Thank you! Works like it used to.

**Comment by danyukezz** [comment]
thanks helped for me as well, version 6.0.7 has the same problem!
